controllers/auth/kakao.auth.controller.js
routes/auth.router.js

FE측 테스트를 위하여 login/:userId로 로그인이 가능했으나
순서를 잘못 설정하여 login/kakao와 충돌,
login/test/:userId로 변경하여 충돌 해결

Fix: 카카오 로그인이 되지 않던 문제

---

controllers/community/comment.community.contorller.js
routes/community.router.js
services/community/comment.community.service.js

- communityId, articleId에 따라 특정 게시글의 댓글만 조회하는 기능입니다.
- 게시글은 있지만 댓글이 없는 경우 204, 게시글 자체가 없는 경우 404를 뱉도록 하였습니다.

[재민] Feat: 댓글 조회 기능

---

controllers/community/article.report.community.controller.js
routes/community.router.js
services/community/article.report.community.service.js

- 게시글을 신고하는 API를 추가하였습니다.
- 자기 자신에 대한 신고일 경우 403, 게시글이 존재하지 않는 경우 404, 동일 대상에 대한 중복 신고일 경우 409로 처리했습니다.

[재민] Feat: 게시글 신고 기능

---

controllers/community/comment.report.community.controller.js
routes/community.router.js
services/community/comment.report.community.service.js

- 게시글을 신고하는 API를 추가하였습니다.
- 자기 자신에 대한 신고일 경우 403, 댓글이 존재하지 않는 경우 404, 동일 대상에 대한 중복 신고일 경우 409로 처리했습니다.

[재민] Feat: 댓글 신고 기능

---

services/community/article.crud.community.service.js
utils/upload/uploader.object.js

- STATIC_FILE_BASE_URL 붙이는 함수를 uploader.object.js에 구현하였습니다.
- 게시글 조회 시 해당 함수를 가져와 쓰도록 하였습니다.

Feat: 사진 정보 가져올 때 base url 붙이는 함수 구현

---

controllers/community/article.aggregate.community.contoller.js
routes/community.router.js
services/community/article.aggregate.community.service.js

- 특정 시간대에 받은 댓글과 좋아요 수를 바탕으로 가장 인기 있는 게시글 2개를 가져오는 API를 구현하였습니다.

Feat: 커뮤니티 인기글 집계 기능

---

models/index.js
routes/swagger.index.js
services/community/article.read.community.service.js

- 익명으로 등록된 게시글의 경우, authorId를 익명처리해서 보내야 함.
- articleComments의 경우, status: deleted를 제외하고 가져오는 것이 아니라 대댓글이 안 달린 deleted는 제거하되, 대댓글이 달린 deleted는 내용만 삭제한 채로 formatting을 해서 응답해야 함.

게시글 검색 관련 버그 수정 및 작성자 정보를 포함하도록 변경

---

routes/events.router.js

이벤트 swagger

---

index.js
utils/options/options.js

"https://peekle-frontend-develop.vercel.app"
url 뒤에 / 가 붙어있던 것을 config.json에서 수정하였습니다.
해당 부분이 원인 ^.^

Feat: cors 에러 관련 수정

---

__tests__/article.aggregate.community.test.js
__tests__/article.crud.community.test.js
__tests__/article.like.community.test.js
__tests__/article.read.community.test.js
__tests__/comment.community.test.js
__tests__/comment.like.community.test.js
__tests__/report.community.test.js
__tests__/sample.test.js
babel.config.json
index.js
jest.config.js
package-lock.json
package.json
services/community/article.crud.community.service.js
services/community/article.read.community.service.js
services/community/comment.community.service.js
services/community/report.community.service.js
utils/path.util.js
utils/sms/coolsms.js

- 우선적으로 Jest와 Supertest 사용 방법에 대해 공부하고 정리해놓도록 하겠습니다.
- Community 파트 테스트 코드 작성
- Jest를 활용한 Community 파트 100% Coverage
- 피클 백엔드 노션 페이지에 Jest 사용 방법 정리해두었습니다.

Test: Community 테스트 코드 작성

---

__tests__/article.aggregate.community.test.js
__tests__/article.crud.community.test.js
__tests__/article.read.community.test.js
__tests__/comment.community.test.js
services/community/article.aggregate.community.service.js
services/community/article.crud.community.service.js
services/community/article.read.community.service.js
services/community/comment.community.service.js

Feat: 게시글 및 댓글 익명 처리

---

services/admin/report.manage.admin.service.js

- cancelled (영국식)
- canceled (미국식)

Refactor: cancelled 미국식으로 수정

---

__tests__/article.crud.community.test.js
__tests__/comment.community.test.js
controllers/community/article.crud.community.controller.js
controllers/community/article.read.community.controller.js
controllers/community/comment.community.controller.js
middleware/authenticate.jwt.js
routes/community.router.js
services/community/article.crud.community.service.js
services/community/article.read.community.service.js
services/community/comment.community.service.js

Feat: 게시글 및 댓글 좋아요 여부 표시

---

controllers/events/create.events.controller.js
controllers/events/detail.events.controller.js
controllers/events/groups.events.controller.js
controllers/events/list.events.controller.js
controllers/events/report.events.controller.js
controllers/events/scrap.events.controller.js
controllers/tickets/create.tickets.controller.js
controllers/tickets/detail.tickets.controller.js
controllers/tickets/list.tickets.controller.js
routes/tickets.router.js
services/events/category.events.service.js
services/events/create.events.service.js
services/events/detail.events.service.js
services/events/list.events.service.js
services/events/report.events.service.js
services/events/scrap.events.service.js
services/tickets/create.tickets.service.js
services/tickets/detail.tickets.service.js
services/tickets/list.tickets.service.js
utils/validators/tickets/tickets.validators.js

이벤트, 티켓 부분 리펙토링

---

services/community/article.crud.community.service.js

updateArticle()에서 isAnonymous에 대한 처리가 없어서 추가하였습니다.

게시글 수정 익명 여부 수정 추가

---

controllers/events/scrap.events.controller.js
controllers/tickets/detail.tickets.controller.js
services/events/list.events.service.js
services/events/scrap.events.service.js
services/tickets/detail.tickets.service.js
services/tickets/list.tickets.service.js

티켓 검토 + 이벤트 스크랩 수정

---

config/config.js
controllers/auth/kakao.auth.controller.js
controllers/users/profile.users.controller.js
models/sql/2025-02-12/before.seed.sql
routes/community.router.js
routes/events.router.js
services/auth/kakao.auth.service.js
services/community/article.crud.community.service.js
services/events/detail.events.service.js

카카오톡 로그인 관련 동작 수정

---

controllers/events/list.events.controller.js
routes/tickets.router.js
services/events/list.events.service.js
utils/swagger/components/parameters.js
utils/swagger/components/paths/events.path.js
utils/swagger/components/paths/index.js
utils/swagger/components/paths/tickets.path.js
utils/swagger/components/schemas/validator.schemas.js
utils/validators/events/events.validators.js
utils/validators/tickets/tickets.validators.js

- tickets.path.js 부분 작업
- event 부분 일부 수정

tickets events 스웨거

---

services/community/article.aggregate.community.service.js
services/community/article.crud.community.service.js
services/community/article.read.community.service.js
services/community/comment.community.service.js

- Merge하는 과정에서 config 파일 import 수정이 안 된 부분이 있어 수정하였습니다.

Fix: config 파일 이동과 관련된 community 코드 수정

---

controllers/community/article.crud.community.controller.js
models/database/CommunitySuggestions.js
models/database/PeeklingChatroom.js
models/database/PeeklingChats.js
models/database/init-models.js
services/community/article.crud.community.service.js
utils/validators/community/article.validators.js

커뮤니티 건의하기 요청 항목 수정

---

models/database/EventSchedules.js
services/community/article.aggregate.community.service.js
services/community/article.crud.community.service.js
services/community/article.read.community.service.js
services/community/comment.community.service.js
services/events/create.events.service.js
services/events/list.events.service.js

이벤트 생성 기존 이미지 수정

---

controllers/community/article.aggregate.community.controller.js
controllers/community/article.read.community.controller.js
routes/community.router.js
services/community/article.aggregate.community.service.js
services/community/article.read.community.service.js
services/community/comment.community.service.js

**탈퇴한 유저(status === terminated)인 경우 닉네임은 `알 수 없음`, 프로필 이미지는 기본 이미지 URL, 사용자 ID는 `null`로 반환.**
- 작성한 글과 댓글은 유지됨.

Community: 탈퇴 사용자 처리

---

controllers/community/article.aggregate.community.controller.js
controllers/community/article.read.community.controller.js
routes/community.router.js
services/community/article.aggregate.community.service.js
services/community/article.read.community.service.js
services/community/comment.community.service.js

**상대방이 나를 차단하거나, 내가 상대방을 차단한 경우 모두 차단 처리.**
- 댓글: content를 차단된 사용자입니다로 반환
- 게시글: 글 자체를 안 보이도록 처리

Community: 차단 사용자 처리
